name: Update last commit time

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  update-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Update README
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          python3 update_time.py
          git diff -- README.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.CHECKER_PAT }}
          add-paths: README.md
          commit-message: "[bot] Update last commit time in README.md"
          author: action-bot <BurtonQin+github-actions[bot]@users.noreply.github.com>
          delete-branch: true
          branch: update-commit-time-preview
          base: master
          title: '[bot] Update last commit time in README.md'
          body: Some checkers recently are updated in their repo activities.
