name: (Preview) Update last commit time

on: push

jobs:
  update-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run update.py
        run: python3 update_time.py && ls -alh && diff README.md test.md --color=always || true
